### PR TITLE
Alvaro

### PR DESCRIPTION
**Pull request by Anieto86**

### CODE REVIEW

**Review by Anieto86 — COMMENTED** [review]
css

**Review by Anieto86 — COMMENTED** [review]
css add

**Review by Anieto86 — COMMENTED** [review]
wuber logo

**Review by Anieto86 — COMMENTED** [review]
alex changes

**Review by Anieto86 — COMMENTED** [review]
css

**Review by Anieto86 — COMMENTED** [review]
div erase

**Review by Alex-Waite — APPROVED** [review]

**Pull request merged**
